"""add_params_to_scenario_and_scene

Revision ID: ecde84362552
Revises: 9815d1506748
Create Date: 2025-11-16 03:42:56.855789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecde84362552'
down_revision: Union[str, None] = '9815d1506748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('scenes', sa.Column('params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'params')
    op.drop_column('scenarios', 'params')
    # ### end Alembic commands ###
