"""add_style_to_shot_version

Revision ID: 205c9abe2944
Revises: 6fb510744f14
Create Date: 2025-11-16 04:22:47.210840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205c9abe2944'
down_revision: Union[str, None] = '6fb510744f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot_versions', sa.Column('style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shot_versions', 'style')
    # ### end Alembic commands ###
