"""add sketch_image middle_image final_image to shot and shot_version

Revision ID: 484f5525394a
Revises: 205c9abe2944
Create Date: 2025-11-16 23:49:40.353599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484f5525394a'
down_revision: Union[str, None] = '205c9abe2944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot_versions', sa.Column('sketch_image', sa.String(), nullable=True))
    op.add_column('shot_versions', sa.Column('middle_image', sa.String(), nullable=True))
    op.add_column('shot_versions', sa.Column('final_image', sa.String(), nullable=True))
    op.drop_column('shot_versions', 'image')
    op.add_column('shots', sa.Column('sketch_image', sa.String(), nullable=True))
    op.add_column('shots', sa.Column('middle_image', sa.String(), nullable=True))
    op.add_column('shots', sa.Column('final_image', sa.String(), nullable=True))
    op.drop_column('shots', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shots', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shots', 'final_image')
    op.drop_column('shots', 'middle_image')
    op.drop_column('shots', 'sketch_image')
    op.add_column('shot_versions', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shot_versions', 'final_image')
    op.drop_column('shot_versions', 'middle_image')
    op.drop_column('shot_versions', 'sketch_image')
    # ### end Alembic commands ###
