"""add_style_to_scenario_scene_shot

Revision ID: 6fb510744f14
Revises: a27a3865b79b
Create Date: 2025-11-16 04:20:42.615928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb510744f14'
down_revision: Union[str, None] = 'a27a3865b79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('style', sa.String(), nullable=True))
    op.add_column('scenes', sa.Column('style', sa.String(), nullable=True))
    op.add_column('shots', sa.Column('style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shots', 'style')
    op.drop_column('scenes', 'style')
    op.drop_column('scenarios', 'style')
    # ### end Alembic commands ###
