"""add_shot_version

Revision ID: a27a3865b79b
Revises: ecde84362552
Create Date: 2025-11-16 04:14:53.519275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27a3865b79b'
down_revision: Union[str, None] = 'ecde84362552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shot_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_versions_id'), 'shot_versions', ['id'], unique=False)
    op.create_index(op.f('ix_shot_versions_is_current'), 'shot_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_shot_versions_shot_id'), 'shot_versions', ['shot_id'], unique=False)
    op.create_index(op.f('ix_shot_versions_version_number'), 'shot_versions', ['version_number'], unique=False)
    op.add_column('shots', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shots_current_version_id'), 'shots', ['current_version_id'], unique=False)
    op.create_foreign_key('shots_current_version_id_fkey', 'shots', 'shot_versions', ['current_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shots_current_version_id_fkey', 'shots', type_='foreignkey')
    op.drop_index(op.f('ix_shots_current_version_id'), table_name='shots')
    op.drop_column('shots', 'current_version_id')
    op.drop_index(op.f('ix_shot_versions_version_number'), table_name='shot_versions')
    op.drop_index(op.f('ix_shot_versions_shot_id'), table_name='shot_versions')
    op.drop_index(op.f('ix_shot_versions_is_current'), table_name='shot_versions')
    op.drop_index(op.f('ix_shot_versions_id'), table_name='shot_versions')
    op.drop_table('shot_versions')
    # ### end Alembic commands ###
